In [15]:
import os
from torch.autograd import Variable
import torch.utils.data
from torch.nn import DataParallel
from config import BATCH_SIZE, PROPOSAL_NUM, test_model
from core import model, dataset
# from core import utils

os.environ['CUDA_VISIBLE_DEVICES'] = '0,1,2,3'
if not test_model:
    raise NameError('please set the test_model file to choose the checkpoint!')

In [16]:
BATCH_SIZE = 16

In [17]:
data_dir = './birds'
# read dataset

testset = dataset.Predict_data(root=data_dir, data_len=None)
testloader = torch.utils.data.DataLoader(testset, batch_size=BATCH_SIZE,
                                         shuffle=False, num_workers=8, drop_last=False)

In [18]:
test_model = 'models/birds'

In [19]:
# define model
net = model.attention_net(topN=PROPOSAL_NUM)
ckpt = torch.load(test_model)
net.load_state_dict(ckpt['net_state_dict'])
net = net.cuda()
# net = DataParallel(net)
creterion = torch.nn.CrossEntropyLoss()

In [20]:
test_loss = 0
test_correct = 0
total = 0
for i, data in enumerate(testloader):
#     if i > 0:
#         break
    with torch.no_grad():
        img, label = data[0].cuda(), data[1].cuda()
        print(data[1])
        batch_size = img.size(0)
        _, concat_logits, _, _, _ = net(img)
#         print (concat_logits)
        # calculate loss
        concat_loss = creterion(concat_logits, label)
        # calculate accuracy
        _, concat_predict = torch.max(concat_logits, 1)
        print (concat_predict.data)
        total += batch_size
        test_correct += torch.sum(concat_predict.data == label.data)
        test_loss += concat_loss.item() * batch_size
#         progress_bar(i, len(testloader), 'eval on test set')

test_acc = float(test_correct) / total
test_loss = test_loss / total
print('test set loss: {:.3f} and test set acc: {:.3f} total sample: {}'.format(test_loss, test_acc, total))

print('finishing testing')

tensor([6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])
tensor([ 8,  1,  1,  7,  5,  5,  3,  6,  6,  2, 10,  6,  4,  1,  0,  4],
       device='cuda:0')
tensor([6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])
tensor([ 6,  7,  7,  1,  1,  7,  8,  7,  5,  8,  8, 10,  2,  3, 10,  2],
       device='cuda:0')
tensor([7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8])
tensor([ 7,  7,  7, 10,  3,  8,  8, 10,  8,  8,  9,  8,  8,  8,  8,  6],
       device='cuda:0')
tensor([8, 8, 8, 8, 8, 8, 8, 5, 5, 5, 5, 5, 5, 5, 5, 5])
tensor([10,  8,  8,  8,  8,  8,  8,  5,  5,  5,  5,  4,  5,  7,  2,  5],
       device='cuda:0')
tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])
tensor([ 9,  6, 10,  5,  9,  0,  7,  9,  8,  0,  8,  7,  0,  4,  4,  7],
       device='cuda:0')
tensor([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1])
tensor([ 8,  8,  3, 10,  3,  3,  3,  8,  5,  6,  8,  5,  3,  0,  9,  1],
       device='cuda:0')
tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 10, 10, 10, 10, 10])
ten

In [8]:
# testset.__getitem__(index=0)

In [57]:
testset.__len__()

3